### ISSUE TITLE
Checklist for finalisation of Oncotools instance

### ISSUE THREAD

**Issue by sveinugu** [FBernal-oPs/Galaxy-OncoTools#1]
@FBernal-oPs Here's a final checklist of features to install/test before Sigve can submit his paper:

- [x] Please add Sigve to this repo, so he can follow the progress of these issues (this should be a simple one)
- [x] The GDPR documentation is now live at https://elixir-oslo.github.io/gdpr/. I was not aware how easy it was to host this on github and I have changed my mind and think it is now better to just use this single URL across all services (if needed, we can move this to e.g. elixir.no later). Meaning that you should remove the `galaxy-term` related config for nginx and the task that creates a local copy of the GDPR repo and instead just point to this URL in the galaxy config (`terms_url: https://elixir-oslo.github.io/gdpr/`). I am not sure whether you needed to add a web hook for the "Help"->"Terms and Conditions" menu option or not. If so, you still need it.
- [x] The welcome page should be updated with a link to the new GDPR page
- [x] Make sure that ID_SECRET and the log encryption passphrase is stored in Ansible vault (and change the latter, as the current passphrase will be compromised if this repo is made public at some point, which I think it should). You might already have done this, but I cannot see it in the current repo. Perhaps you have not pushed these changes?
- [ ] Have you tested my production server settings yet? I highly suggest you try them out, and if there are any issues, you can revert to the current ones?
- [x] Regarding smtp solution. I have no updates from USIT. Still this is only really needed for sending out password change mails to external users. I think it should be possible to send emails to local UIO-managed addresses out-of-the-box using `localhost`. Could you try to set up the bug reporting solution using `smtp_server: localhost` and `error_email_to: oslo-services@elixir.no` (I have now requested for this to be created)? And test that this actually works but submitting a bug report on a red history box (if you have one).
- [x] Add a note to the welcome page that explains that the automatic system for password change is not working, so in case of the need of password change or other types of technical assistance, please contact us at oslo-services@elixir.no. 
- [x] Sigve wants a link from the welcome page to the OncoEnrichR tool. This should be possible to do with the following: ```<a href="../tool_runner?tool_id=galaxy-ntnu.bioinfo.no%2Ftoolshed_nels%2Frepos%2Fradmilko%2Foncoenrichr%2Foncoenrichr_wrapper" target="_top"> text </a>``` Sigve probably has some opinions on where/how this link should be added. 

Anything else?

**Comment by sveinugu** [comment]
@FBernal-oPs, some comments:

1. The URL in the menu item "Help" -> "Terms and Conditions" is still the old URL
2. The passphrase fro log rotation does not seem to have been added to Ansible vault (and changed) yet. https://github.com/FBernal-oPs/Galaxy-OncoTools/commit/681b511109fe919f261c36d09db03ecc79f268f6#r52760870
3. The smtp server should be `localhost`. `smtp.uio.no` will not work (I added that in a previous version of the issue by mistake). Please test mail sending from both the command line and as a bug report from galaxy. You would need `sendmail` installed on the server for this to work, I believe.
4. As regards the notice on the webpage. What about: 'NB: Please note that the feature to reset user passwords does not currently work. If you need help with this or have any other requests, please send a mail to oslo-services@elixir.no'?

**Comment by FBernal-oPs** [comment]
Comments 1,2 and 4 are resolved. For 3 comment the smtp server is now set to `localhost` but testing is still missing

**Comment by sveinugu** [comment]
@FBernal-oPs To test mail sending from the command line:
```
python -c "from smtplib import SMTP; s = SMTP('localhost'); frm = 'no-reply@oncotools.elixir.no'; to = 'oslo-services@elixir.no'; subject = 'Test email'; body = 'Test text'; s.sendmail(frm, to, 'From: {}\nTo: {}\nSubject: {}\n{}'.format(frm, to, subject, body))"
```
(copied from slack)

**Comment by sveinugu** [comment]
- [ ] The terms_url should have been set to https://elixir-oslo.github.io/gdpr/ not https://elixir-oslo.github.io/gdpr/tos.html
- [ ] Error emails are still not being sent correctly.
